# Generated by Django 3.2.4 on 2021-06-26 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppinglist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='purchased',
            field=models.BooleanField(default=None),
            preserve_default=False,
        ),
    ]
